on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Excavator
        uses: ScoopInstaller/GithubActions@main
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
